version: '2'
services:
  caesar-cipher:
    build: .
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      JAVA_OPTS: "-Dlogging.level.com.caesarcipher=INFO
                  -DLOG_ROOT_LEVEL=INFO
                  -Djava.security.egd=file:/dev/./urandom
                  -Dlogging.file=/tmp/caesar-cipher.log"